### ISSUE TITLE
Plasma Integration

### ISSUE THREAD

**Issue by ZiadEl-kashif** [flathub/com.microsoft.Edge#202]
the Plasma Integration extension is not working 
Kubuntu 22.04
KDE 5.25.5
Edge Flatpak V 105.0.1343.50-1

**Comment by TheEvilSkeleton** [comment]
If any Plasma user could help with this, then I'd appreciate it. I don't really know anything about Plasma so I can't really help here.

**Comment by TheEvilSkeleton** [comment]
Fixed by https://github.com/flathub/com.microsoft.Edge/pull/247

**Comment by sbancuz** [comment]
Hi, was trying edge but the Plasma Integration Extension from the microsoft store still doesn't work. Do i have to install the one from the chrome strore?

I'm on plasma 5.27.4
