### ISSUE TITLE
Microsoft Edge Flatpak Beta shows two icons in taskbar on KDE Fedora

### ISSUE THREAD

**Issue by Wladefant** [flathub/com.microsoft.Edge#309]
When I open Microsoft Edge Flatpak Beta on KDE Fedora from Flathub-beta, it first shows two icons in the taskbar. One normal Edge icon and the other one the Edge Beta icon. After that, the Edge Beta icon disappears and the normal icon is showing. This does not happen with the official Edge installation from Microsoft. This issue occurs every time I open Edge Flatpak Beta.

Steps to reproduce:
1. Install Microsoft Edge Flatpak Beta from Flathub-beta
2. 2. Open Microsoft Edge Flatpak Beta from the application launcher or terminal.
3. Observe the taskbar and notice two icons appearing briefly.

Expected behavior: Only one icon should appear in the taskbar when opening Microsoft Edge Flatpak Beta.

Actual behavior: Two icons appear in the taskbar when opening Microsoft Edge Flatpak Beta.

Screen recording:will be appended later, when spectacle updates to 22.04 ;)

System information:
- KDE Plasma version: plasmashell 5.27.4
- Fedora version: 38
- Microsoft Edge version: Version 113.0.1774.23 (from install)

**Comment by evan-a-a** [comment]
@Wladefant Are you able to reproduce this on the latest version of beta? Chromium's wayland implementation has matured quite a bit since 113 and this could've been fixed in the process.

**Comment by Wladefant** [comment]
Yes just installed a fresh fedora kde. Have only installed edge beta and still a problem
[Screencast_20231104_135252.webm](https://github.com/flathub/com.microsoft.Edge/assets/79611093/4cb116ef-2492-4ce9-82b5-b4f6e588d945)

**Comment by Wladefant** [comment]
Thank you, it works now
